### ISSUE TITLE
Unidad4_Ingenieria_de_Software

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Nelsy21#1]
[Infografia_Unidad4_Ingenieria_de_Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Nelsy21/files/15461450/Infografia_Unidad4_Ingenieria_de_Software.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado Calificacion 20
